import './globals.css'
import Header from '@/components/header'
import Providers from './providers'
import Navbar from '@components/navbar'
import SearchBar from '@components/search-bar'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Providers>
          <Header />
          <Navbar />
          <SearchBar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
